// ─────────────────────────────────────────────────────────────────────────────
// CONFIG — every timing (seconds, scene-local), position and line of copy.
// Scenes and components read from here; nothing is hardcoded downstream.
// ─────────────────────────────────────────────────────────────────────────────

const FPS = 30;

/** Seconds → frames. */
export const sec = (s: number) => Math.round(s * FPS);

// The referral program's numbers, as in the c4c.club app (src/lib/domain/constants.ts).
const REFERRAL = {
	signupBonus: 50, // SIGNUP_BONUS_CREDITS
	inviteBonus: 25, // REFERRAL_SIGNUP_BONUS_CREDITS: for them
	advertiserReward: 20, // REFERRAL_ADVERTISER_REWARD_CREDITS: for you
	publisherReward: 50, // REFERRAL_PUBLISHER_REWARD_CREDITS: for you
	qualifying: 10, // REFERRAL_QUALIFYING_CREDITS
} as const;

export const CONFIG = {
	video: {id: 'C4CReferral', width: 1920, height: 1080, fps: FPS, durationInSeconds: 30},

	referral: REFERRAL,

	// Brand: c4c.club dark theme (src/app/globals.css in the app), converted from oklch.
	// Fonts are loaded in src/fonts.ts (Bricolage Grotesque display, Figtree text).
	brand: {
		bg: '#0B0A16',
		black: '#05040C',
		surface: '#161524',
		surfaceHi: '#1D1C2D',
		line: '#2A2842',
		lineHi: '#3D3A63',
		text: '#F3F3F9',
		muted: '#A0A1B6',
		// Brand gradient, purple → blue. `fill*` stops keep white text above 5:1.
		purple: '#6A3FD0',
		violet: '#5953CF',
		blue: '#4E80F5',
		fillFrom: '#492490',
		fillTo: '#3464DB',
		textFrom: '#AE99FB',
		textTo: '#8DBBFF',
		accent: '#7591FE', // primary: lines, focus
		pop: '#FF8F49', // warm accent: reserved for credits and moments of delight
		green: '#43BE79',
		amber: '#F6B044',
		red: '#FF6467',
	},

	// Continuous backdrop behind every scene. Glow keyframes are global seconds.
	backdrop: {
		glow: [
			{at: 0, v: 0.3},
			{at: 4, v: 0.7},
			{at: 9, v: 1},
			{at: 13.5, v: 0.8},
			{at: 20, v: 1.2},
			{at: 22, v: 0.6},
			{at: 26, v: 1},
			{at: 29, v: 1.35},
		],
		grid: {gap: 44, dot: 1.4, opacity: 0.35},
		grain: 0.07,
		vignette: 0.75,
	},

	// Scene-to-scene transitions, keyed by the scene that enters.
	// `iris`: opens as a circle with a glowing edge from `origin` (screen px).
	// `push`: slides in from the right, un-blurring, over the outgoing scene.
	transitions: {
		dur: 0.6,
		sink: {scale: 0.92, dim: 0.35},
		push: {distance: 520, blur: 24},
		join: {type: 'iris', origin: {x: 1480, y: 600}},
		reward: {type: 'push'},
		fair: {type: 'iris', origin: {x: 960, y: 540}},
		cta: {type: 'push'},
	},

	motion: {
		// "Things arriving" spring. No overshoot-heavy bounce: damping ~14.
		spring: {damping: 14, stiffness: 120, mass: 0.9},
	},

	assets: {
		icon: 'icon.svg',
		wordmark: 'wordmark-on-dark.svg',
	},

	// Sounds live in public/sfx/, generated by scripts/make-audio.py (`npm run audio`).
	// Cue timings are derived from the scene schedules in src/audio/cues.ts.
	audio: {
		dir: 'sfx',
		music: {file: 'music.wav', volume: 0.5},
		// Per-sound volume (0–1), applied on top of each file's own level.
		volumes: {
			pop: 0.45,
			tick: 0.3,
			whoosh: 0.45,
			send: 0.35,
			land: 0.4,
			coin: 0.5,
			confirm: 0.55,
			wait: 0.45,
			deny: 0.6,
			fill: 0.22,
			hit: 0.85,
		},
		whooshLead: 0.3, // whooshes start this many seconds before the cut they cover
	},

	// The two founders in the story.
	you: {name: 'Brewlog', monogram: 'B', color: '#6B4226'},
	friend: {name: 'Kiln', domain: 'kiln.studio', monogram: 'K', color: '#6C8CFF', ad: 'Pottery class bookings, sorted.'},

	scenes: {
		hook: {
			start: 0,
			duration: 4,
			line1: 'Know a founder with a project?',
			accentWord: 'founder',
			line2: 'Bring them into the club. You both get credits.',
			line2Accent: 'credits.',
			wordsAt: 0.3,
			wordStagger: 0.2,
			sweepAt: 1.7,
			sweepDur: 0.9,
			line2At: 2.1,
			line2Fade: 0.5,
			drift: 0.04,
			fadeOutAt: 3.55,
			fadeOutDur: 0.45,
			exitScale: 1.6,
			exitBlur: 18,
		},

		link: {
			start: 4,
			duration: 5,
			kicker: 'Invite founders',
			caption: 'Copy your invite link.',
			captionAccent: ['invite', 'link.'],
			fieldLabel: 'Your invite link',
			url: 'c4c.club/invite/k7Qp2xBa',
			copy: 'Copy',
			copied: 'Copied',
			panel: {w: 1040, h: 560, x: 960, y: 600},
			friendCard: {w: 520, h: 330, x: 1480, y: 600},
			panelAt: 0,
			captionAt: 0.25,
			fieldAt: 0.5,
			cursor: {from: {x: 1560, y: 980}, at: 1.1, moveDur: 0.8},
			clickAt: 2.0,
			// The link lifts out of the field and flies to the friend's inbox on the right.
			friendAt: 2.2,
			slideDur: 0.5,
			slideLeft: 380, // the panel slides left to make room for the friend
			sendAt: 2.8,
			flightDur: 0.8,
			arc: 240, // how high the link arcs on its way over (px)
			deliveredLabel: 'Invite from Brewlog',
		},

		join: {
			start: 9,
			duration: 4.5,
			caption: 'They join with extra credits.',
			captionAccent: ['extra', 'credits.'],
			captionAt: 0.3,
			cardAt: 0.2,
			welcomeAt: 0.9, // welcome credits count up
			welcomeDur: 0.7,
			bonusAt: 1.9, // the invite bonus lands on top
			bonusDur: 0.8,
			coins: 5,
			coinStagger: 0.08,
			tagAt: 2.9,
			welcomeLabel: 'welcome credits',
			bonusLabel: 'invite bonus',
			tag: 'for them',
		},

		reward: {
			start: 13.5,
			duration: 8.5,
			caption: 'Then you get paid when they take part.',
			captionAccent: ['you', 'get', 'paid'],
			captionAt: 0.15,
			balanceAt: 0.3,
			balanceLabel: 'Your invite rewards',
			// Each path: the friend's approved clicks fill toward 10 credits, then pays you.
			paths: [
				{
					key: 'advertiser',
					title: 'Their ad runs on the network',
					progressLabel: 'spent on approved clicks',
					reward: REFERRAL.advertiserReward,
					badge: null,
					at: 1.0,
				},
				{
					key: 'publisher',
					title: 'Their site hosts members’ ads',
					progressLabel: 'earned hosting ads',
					reward: REFERRAL.publisherReward,
					badge: 'Pays the most',
					at: 3.4,
				},
			],
			fillDelay: 0.5,
			fillDur: 1.4,
			payDelay: 0.15, // after the bar fills
			coinFlight: 0.7,
			coinsPerReward: 6,
			coinStagger: 0.06,
			tag: 'for you',
		},

		fair: {
			start: 22,
			duration: 4,
			headline: 'Only real traffic counts.',
			headlineAccent: ['real', 'traffic'],
			headlineAt: 0.1,
			rowsAt: 0.7,
			rowStagger: 0.45,
			verdictDelay: 0.35,
			rows: [
				{label: 'Clicks with other members', verdict: 'Counts', ok: true},
				{label: 'Clicks on your own site', verdict: "Doesn't count", ok: false},
				{label: 'Clicks with people you invited', verdict: "Doesn't count", ok: false},
			],
			footnote: 'Rewards pay out once clicks clear review.',
			footnoteAt: 2.4,
		},

		cta: {
			start: 26,
			duration: 4,
			wordmarkAt: 0.15,
			wordmarkWidth: 520,
			shineAt: 0.8,
			shineDur: 0.8,
			taglineAt: 0.4,
			tagline: `Earn up to ${REFERRAL.advertiserReward + REFERRAL.publisherReward} credits per founder you invite.`,
			taglineAccent: [`${REFERRAL.advertiserReward + REFERRAL.publisherReward}`, 'credits'],
			buttonAt: 0.7,
			buttonShineAt: 1.5,
			button: 'Get your invite link',
			urlAt: 0.9,
			url: 'c4c.club/dashboard/credits',
		},
	},
} as const;

export type SceneKey = keyof typeof CONFIG.scenes;
